import React from 'react';
import Card from './card.js';

export default function Board() {
  return (
    <div id="board-wrapper">
      <Card className="card corner">🃟</Card>
      <Card className="card spades 2">🂢</Card>
      <Card className="card spades 3">🂣</Card>
      <Card className="card spades 4">🂤</Card>
      <Card className="card spades 5">🂥</Card>
      <Card className="card spades 6">🂦</Card>
      <Card className="card spades 7">🂧</Card>
      <Card className="card spades 8">🂨</Card>
      <Card className="card spades 9">🂩</Card>
      <Card className="card corner">🃟</Card>
      <Card className="card clubs 6">🃖</Card>
      <Card className="card clubs 5">🃕</Card>
      <Card className="card clubs 4">🃔</Card>
      <Card className="card clubs 3">🃓</Card>
      <Card className="card clubs 2">🃒</Card>
      <Card className="card hearts a">🂱</Card>
      <Card className="card hearts k">🂾</Card>
      <Card className="card hearts q">🂽</Card>
      <Card className="card hearts 10">🂺</Card>
      <Card className="card spades 10">🂪</Card>
      <Card className="card clubs 7">🃗</Card>
      <Card className="card spades a">🂡</Card>
      <Card className="card diamonds 2">🃂</Card>
      <Card className="card diamonds 3">🃃</Card>
      <Card className="card diamonds 4">🃄</Card>
      <Card className="card diamonds 5">🃅</Card>
      <Card className="card diamonds 6">🃆</Card>
      <Card className="card diamonds 7">🃇</Card>
      <Card className="card heart 9">🂹</Card>
      <Card className="card spades q">🂭</Card>
      <Card className="card clubs 8">🃘</Card>
      <Card className="card spades k">🂮</Card>
      <Card className="card clubs 6">🃖</Card>
      <Card className="card clubs 5">🃕</Card>
      <Card className="card clubs 4">🃔</Card>
      <Card className="card clubs 3">🃓</Card>
      <Card className="card clubs 2">🃒</Card>
      <Card className="card diamonds 8">🃈</Card>
      <Card className="card hearts 8">🂸</Card>
      <Card className="card spades k">🂮</Card>
      <Card className="card clubs 9">🃙</Card>
      <Card className="card spades q">🂭</Card>
      <Card className="card clubs 7">🃗</Card>
      <Card className="card hearts 6">🂶</Card>
      <Card className="card hearts 5">🂵</Card>
      <Card className="card hearts 4">🂴</Card>
      <Card className="card hearts a">🂱</Card>
      <Card className="card diamonds 9">🃉</Card>
      <Card className="card hearts 7">🂷</Card>
      <Card className="card spades a">🂡</Card>
      <Card className="card clubs 10">🃚</Card>
      <Card className="card spades 10">🂪</Card>
      <Card className="card clubs 8">🃘</Card>
      <Card className="card hearts 7">🂷</Card>
      <Card className="card hearts 2">🂲</Card>
      <Card className="card hearts 3">🂳</Card>
      <Card className="card hearts k">🂾</Card>
      <Card className="card diamonds 10">🃊</Card>
      <Card className="card hearts 6">🂶</Card>
      <Card className="card diamonds 2">🃂</Card>
      <Card className="card clubs q">🃝</Card>
      <Card className="card hearts 9">🂹</Card>
      <Card className="card clubs 9">🃙</Card>
      <Card className="card hearts 8">🂸</Card>
      <Card className="card hearts 9">🂹</Card>
      <Card className="card hearts 10">🂺</Card>
      <Card className="card hearts q">🂽</Card>
      <Card className="card diamonds q">🃍</Card>
      <Card className="card hearts 5">🂵</Card>
      <Card className="card diamonds 3">🃃</Card>
      <Card className="card clubs k">🃞</Card>
      <Card className="card hearts 8">🂸</Card>
      <Card className="card clubs 10">🃚</Card>
      <Card className="card clubs q">🃝</Card>
      <Card className="card clubs k">🃞</Card>
      <Card className="card clubs a">🃑</Card>
      <Card className="card diamonds a">🃁</Card>
      <Card className="card diamonds k">🃎</Card>
      <Card className="card hearts 4">🂴</Card>
      <Card className="card diamonds 4">🃄</Card>
      <Card className="card clubs a">🃑</Card>
      <Card className="card spades 7">🂧</Card>
      <Card className="card spades 6">🂦</Card>
      <Card className="card spades 5">🂥</Card>
      <Card className="card spades 4">🂤</Card>
      <Card className="card spades 3">🂣</Card>
      <Card className="card spades 2">🂢</Card>
      <Card className="card hearts 2">🂲</Card>
      <Card className="card hearts 3">🂳</Card>
      <Card className="card diamonds 5">🃅</Card>
      <Card className="card corner">🃟</Card>
      <Card className="card diamonds a">🃁</Card>
      <Card className="card diamonds k">🃎</Card>
      <Card className="card diamonds q">🃍</Card>
      <Card className="card diamonds 10">🃊</Card>
      <Card className="card diamonds 9">🃉</Card>
      <Card className="card diamonds 8">🃈</Card>
      <Card className="card diamonds 7">🃇</Card>
      <Card className="card diamonds 6">🃆</Card>
      <Card className="card corner">🃟</Card>
    </div>
  );
}
