import React from 'react';
import Card from './card.js';

export default function Board(props) {
  return (
    <div id="board-wrapper">
      <Card className="card corner"></Card>
      <Card className="card spades-2" selected={props.selected}></Card>
      <Card className="card spades-3" selected={props.selected}></Card>
      <Card className="card spades-4" selected={props.selected}></Card>
      <Card className="card spades-5" selected={props.selected}></Card>
      <Card className="card spades-6" selected={props.selected}></Card>
      <Card className="card spades-7" selected={props.selected}></Card>
      <Card className="card spades-8" selected={props.selected}></Card>
      <Card className="card spades-9" selected={props.selected}></Card>
      <Card className="card corner"></Card>
      <Card className="card clubs-6" selected={props.selected}></Card>
      <Card className="card clubs-5" selected={props.selected}></Card>
      <Card className="card clubs-4" selected={props.selected}></Card>
      <Card className="card clubs-3" selected={props.selected}></Card>
      <Card className="card clubs-2" selected={props.selected}></Card>
      <Card className="card hearts-a" selected={props.selected}></Card>
      <Card className="card hearts-k" selected={props.selected}></Card>
      <Card className="card hearts-q" selected={props.selected}></Card>
      <Card className="card hearts-10" selected={props.selected}></Card>
      <Card className="card spades-10" selected={props.selected}></Card>
      <Card className="card clubs-7" selected={props.selected}></Card>
      <Card className="card spades-a" selected={props.selected}></Card>
      <Card className="card diamonds-2" selected={props.selected}></Card>
      <Card className="card diamonds-3" selected={props.selected}></Card>
      <Card className="card diamonds-4" selected={props.selected}></Card>
      <Card className="card diamonds-5" selected={props.selected}></Card>
      <Card className="card diamonds-6" selected={props.selected}></Card>
      <Card className="card diamonds-7" selected={props.selected}></Card>
      <Card className="card hearts-9" selected={props.selected}></Card>
      <Card className="card spades-q" selected={props.selected}></Card>
      <Card className="card clubs-8" selected={props.selected}></Card>
      <Card className="card spades-k" selected={props.selected}></Card>
      <Card className="card clubs-6" selected={props.selected}></Card>
      <Card className="card clubs-5" selected={props.selected}></Card>
      <Card className="card clubs-4" selected={props.selected}></Card>
      <Card className="card clubs-3" selected={props.selected}></Card>
      <Card className="card clubs-2" selected={props.selected}></Card>
      <Card className="card diamonds-8" selected={props.selected}></Card>
      <Card className="card hearts-8" selected={props.selected}></Card>
      <Card className="card spades-k" selected={props.selected}></Card>
      <Card className="card clubs-9" selected={props.selected}></Card>
      <Card className="card spades-q" selected={props.selected}></Card>
      <Card className="card clubs-7" selected={props.selected}></Card>
      <Card className="card hearts-6" selected={props.selected}></Card>
      <Card className="card hearts-5" selected={props.selected}></Card>
      <Card className="card hearts-4" selected={props.selected}></Card>
      <Card className="card hearts-a" selected={props.selected}></Card>
      <Card className="card diamonds-9" selected={props.selected}></Card>
      <Card className="card hearts-7" selected={props.selected}></Card>
      <Card className="card spades-a" selected={props.selected}></Card>
      <Card className="card clubs-10" selected={props.selected}></Card>
      <Card className="card spades-10" selected={props.selected}></Card>
      <Card className="card clubs-8" selected={props.selected}></Card>
      <Card className="card hearts-7" selected={props.selected}></Card>
      <Card className="card hearts-2" selected={props.selected}></Card>
      <Card className="card hearts-3" selected={props.selected}></Card>
      <Card className="card hearts-k" selected={props.selected}></Card>
      <Card className="card diamonds-10" selected={props.selected}></Card>
      <Card className="card hearts-6" selected={props.selected}></Card>
      <Card className="card diamonds-2" selected={props.selected}></Card>
      <Card className="card clubs-q" selected={props.selected}></Card>
      <Card className="card spades-9" selected={props.selected}></Card>
      <Card className="card clubs-9" selected={props.selected}></Card>
      <Card className="card hearts-8" selected={props.selected}></Card>
      <Card className="card hearts-9" selected={props.selected}></Card>
      <Card className="card hearts-10" selected={props.selected}></Card>
      <Card className="card hearts-q" selected={props.selected}></Card>
      <Card className="card diamonds-q" selected={props.selected}></Card>
      <Card className="card hearts-5" selected={props.selected}></Card>
      <Card className="card diamonds-3" selected={props.selected}></Card>
      <Card className="card clubs-k" selected={props.selected}></Card>
      <Card className="card spades-8" selected={props.selected}></Card>
      <Card className="card clubs-10" selected={props.selected}></Card>
      <Card className="card clubs-q" selected={props.selected}></Card>
      <Card className="card clubs-k" selected={props.selected}></Card>
      <Card className="card clubs-a" selected={props.selected}></Card>
      <Card className="card diamonds-a" selected={props.selected}></Card>
      <Card className="card diamonds-k" selected={props.selected}></Card>
      <Card className="card hearts-4" selected={props.selected}></Card>
      <Card className="card diamonds-4" selected={props.selected}></Card>
      <Card className="card clubs-a" selected={props.selected}></Card>
      <Card className="card spades-7" selected={props.selected}></Card>
      <Card className="card spades-6" selected={props.selected}></Card>
      <Card className="card spades-5" selected={props.selected}></Card>
      <Card className="card spades-4" selected={props.selected}></Card>
      <Card className="card spades-3" selected={props.selected}></Card>
      <Card className="card spades-2" selected={props.selected}></Card>
      <Card className="card hearts-2" selected={props.selected}></Card>
      <Card className="card hearts-3" selected={props.selected}></Card>
      <Card className="card diamonds-5" selected={props.selected}></Card>
      <Card className="card corner" selected={props.selected}></Card>
      <Card className="card diamonds-a" selected={props.selected}></Card>
      <Card className="card diamonds-k" selected={props.selected}></Card>
      <Card className="card diamonds-q" selected={props.selected}></Card>
      <Card className="card diamonds-10" selected={props.selected}></Card>
      <Card className="card diamonds-9" selected={props.selected}></Card>
      <Card className="card diamonds-8" selected={props.selected}></Card>
      <Card className="card diamonds-7" selected={props.selected}></Card>
      <Card className="card diamonds-6" selected={props.selected}></Card>
      <Card className="card corner"></Card>
    </div>
  );
}
